version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db

  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env  # Optionally, use the same .env for pgAdmin settings
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050 of your host machine
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
  
  backup:
  build:
    context: .   # Use the current directory as the build context
    dockerfile: Dockerfile.backup  # Reference the new Dockerfile
  volumes:
    - /var/backups/postgres:/backups/  
  environment:
    POSTGRES_HOST: db
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  depends_on:
    - db

